gui:
  title: "Players"
  description--tp-random: "/tp @r"

messages:
  player-only:
    ja: "{$red}[エラー] プレイヤーのみこのコマンドの実行を許可されています。"
    en: "{$red}[ERROR] Players can only execute this command."
  teleport-success:
    ja: "{$green}%s に TP しました。"
    en: "{$green}Teleported to %s."
  teleport-success--to-you:
    ja: "{$green}%s を自分に TP させました"
    en: "{$green}Teleported %s to yourself."
  teleport-success--you-re-tpd:
    ja: "{$dark_green}%s に TP しました。"
    en: "{$dark_green}Teleported to %s."
  teleport-failure--no-other-players:
    ja: "{$yellow}[失敗] オンラインのプレイヤーがいません。"
    en: "{$yellow}[FAILURE] There's no players online."
  teleport-failure--target-offline:
    ja: "{$yellow}[失敗] %s はオフラインです。"
    en: "{$yellow}[FAILURE] %s is OFFLINE."
