name: KingShiraishi__MCPlugins_TPHelper
main: com.kingshiraishi.mcp_tphelper.TPHelper
version: 1.1.1
api-version: 1.14
commands:
  tplist:
    description: Shows a custom GUI that helps your TP.
    aliases:
      - tplist
      - tl
      - tphelper
      - th
    usage: /tplist
